# Generated by Django 2.2.4 on 2021-01-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_address',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
