# Generated by Django 2.2.4 on 2021-01-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merch_items', models.ManyToManyField(related_name='carts', to='purchase.Merch')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='purchase.Order')),
            ],
        ),
    ]
