# Generated by Django 2.2.4 on 2021-01-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='credit_cart',
            new_name='credit_card',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='merch_items',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='purchase.Cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
