# Generated by Django 2.2.4 on 2021-01-28 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210127_2019'),
        ('purchase', '0003_auto_20210127_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='merch_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='login.User'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='purchase.Cart')),
                ('merch_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='purchase.Merch')),
            ],
        ),
    ]
